name: lint
on:
    push:
      branches:
      - master
    pull_request:
      branches:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: yarn
      - name: lint
        run: yarn lint
